name: Verilator Lint CI

on:
  push:
    branches: [ pipeline, processor-toolchain, main ]
  pull_request:
    branches: [ pipeline, main ]

jobs:
  lint-sv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Verilator
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator

      - name: Run SystemVerilog Lint
        run: |
          make lint
